# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: TonSinsombat

description: เพ้อเจ้อ
author:
  name: Sinsombat Jintavanich (Ton)
  email: sinsombat.j@gmail.com
  github: sinsombatj/
  twitter: sinsombat
  facebook: sinsombat
  linkedin: Sinsombat Jintavanich
  bio: SKN26 KU68 KU73
  picprohead: picprohead2.png

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
